version: '3'

services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock
    restart: always
    ports:
      - "19132:19132/udp"
    environment:
      - EULA=TRUE
      - SERVER_NAME=My Minecraft Server
      - LEVEL_NAME=My Minecraft World
      - DIFFICULTY=normal
      - GAMEMODE=survival
      - SERVER_PORT=19132
      - VIEW_DISTANCE=32
      - ALLOW_CHEATS=false
    volumes:
      - "./data:/data"
